### ISSUE TITLE
PDX Search and PDX Like Me links do not work either

### ISSUE THREAD

**Issue by DABegley** [mgijax/mtb-wi#21] opened 2020-07-07 14:22 UTC
PDX search link give sme a blank blue page. PDX Like Me gives a 500 error.

**Comment by ahcurrier** [comment] 2020-07-08 16:27
This may be caused by master code for PDX needing to be merged into the dev branch. @sneuhaus — how would you like to handle this merge?

**Comment by ahcurrier** [comment] 2020-07-09 17:23
Merge is now done and these work. I'm updating the CSS for the PDX Like Me page to work with the new header and footer.

**Closed** 2020-07-09 17:42 UTC
