### ISSUE TITLE
Link to Tumor Frequency Grid give 500 error

### ISSUE THREAD

**Issue by CarolBult** [mgijax/mtb-wi#20] opened 2020-07-07 11:21 UTC
Linking to the Tumor Frequency Grid [http://bhmtbdb01:8080/mtbwi2/dynamicGrid.do](url) gives a 500 error.

**Comment by ahcurrier** [comment] 2020-07-08 16:27
This may be caused by master code for the grid needing to be merged into the dev branch. @sneuhaus — how would you like to handle this merge?

**Comment by ahcurrier** [comment] 2020-07-09 17:22
Merge is now done. I'm working to update the CSS for this page so that it works with the new header and footer.

**Closed** 2020-07-09 17:42 UTC
